package root:main;

world root {
  import wasi:io/io;
  export component:main/main;
}

world imports {
  import proxy:recorder/%record@0.1.0;
  import wasi:io/io;
  export wrapped-wasi:io/io;
}

world exports {
  import proxy:recorder/%record@0.1.0;
  import wasi:io/io;
  import wrapped-wasi:io/io;
  import wrapped-component:main/main;
  export component:main/main;
}

